USE DatabaseAlex6;
GO 

DELETE FROM Lab6.STUDENTS;
GO 
DELETE FROM Lab6.GROUPS;  
GO 

INSERT INTO Lab6.GROUPS VALUES ('iu9-51', 'nika', 0, 0, 'Skorb'), ('iu9-52', 'janush', 0, 0, 'Dubashka'), ('iu9-53', 'dima', 0, 0, 'Golub');

INSERT INTO Lab6.STUDENTS VALUES ('sasha', 19, 1, 'Chelyabinsk', 'iu9-52'), ('alena', 20, 1, 'Novgorod', 'iu9-51'),
('ilya', 20, 0, 'Belgorod', 'iu9-53'), ('filon', 20, 0, 'Moscow', 'iu9-51');
GO


--NONREPEATABLE READ CHECK

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--WAITFOR DELAY '00:00:05';
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--COMMIT TRANSACTION;
--GO


--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--WAITFOR DELAY '00:00:05';
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--WAITFOR DELAY '00:00:05';
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--COMMIT TRANSACTION;
--GO


--NOT POSSIBLE
--CHANGES WITHIN TRANSACTION

--SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--WAITFOR DELAY '00:00:05';
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
GO
BEGIN TRANSACTION;
SELECT * FROM Lab6.GROUPS;
SELECT * FROM Lab6.STUDENTS;
WAITFOR DELAY '00:00:05';
SELECT * FROM Lab6.GROUPS;
SELECT * FROM Lab6.STUDENTS;
COMMIT TRANSACTION;
GO