USE DatabaseAlex6;
GO 


--NONREPEATABLE READ CHECK

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--GO
--BEGIN TRANSACTION;

--UPDATE Lab6.STUDENTS
--SET Budget = 1
--WHERE Lab6.STUDENTS.PlaceOfBirth <> 'Moscow'

--DELETE FROM Lab6.GROUPS  
--WHERE GroupName = 'iu9-51';  

--COMMIT TRANSACTION;
--GO

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--GO
--BEGIN TRANSACTION;
--UPDATE Lab6.STUDENTS
--SET Budget = 1
--WHERE Lab6.STUDENTS.PlaceOfBirth <> 'Moscow'

--DELETE FROM Lab6.GROUPS  
--WHERE GroupName = 'iu9-51';  
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE 
--WAITS TILL FIRST TRANSACTION

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--GO
--BEGIN TRANSACTION;
--UPDATE Lab6.STUDENTS
--SET Budget = 1
--WHERE Lab6.STUDENTS.PlaceOfBirth <> 'Moscow'

--DELETE FROM Lab6.GROUPS  
--WHERE GroupName = 'iu9-51';  
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE
--CHANGES WITHIN TRANSACTION

--SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
--GO
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--BEGIN TRANSACTION;
--UPDATE Lab6.STUDENTS
--SET Budget = 1
--WHERE Lab6.STUDENTS.PlaceOfBirth <> 'Moscow'

--DELETE FROM Lab6.GROUPS  
--WHERE GroupName = 'iu9-51';  
--COMMIT TRANSACTION;
--GO
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;


--NOT POSSIBLE 
--WAITS TILL FIRST TRANSACTION

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
GO
BEGIN TRANSACTION;
UPDATE Lab6.STUDENTS
SET Budget = 1
WHERE Lab6.STUDENTS.PlaceOfBirth <> 'Moscow'

DELETE FROM Lab6.GROUPS  
WHERE GroupName = 'iu9-51';  
COMMIT TRANSACTION;
GO

