USE DatabaseAlex6;
GO 

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--GO
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE
--WAIT TILL FIRST TRANSACTION
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--GO
--COMMIT TRANSACTION;
--GO


--NOT POSSIBLE
--WAIT TILL FIRST TRANSACTION

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--GO
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE
--CHANGES WITHIN TRANSACTION

SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
GO
BEGIN TRANSACTION;
SELECT * FROM Lab6.GROUPS;
SELECT * FROM Lab6.STUDENTS;
GO
COMMIT TRANSACTION;
GO


--NOT POSSIBLE
--WAITS UNTIL FIRST TRANSACTION

--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--GO
--BEGIN TRANSACTION;
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--GO
--COMMIT TRANSACTION;
--GO