USE DatabaseAlex6;
GO 

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--GO
--BEGIN TRANSACTION;
--INSERT INTO Lab6.GROUPS VALUES ('iu9-54', 'starosta4', 0, 0, 'Magazoff');
--INSERT INTO Lab6.STUDENTS VALUES ('daniil', 20, 1, 'Belgorod', 'iu9-52');
--GO
--COMMIT TRANSACTION;
--GO

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--GO
--BEGIN TRANSACTION;
--INSERT INTO Lab6.GROUPS VALUES ('iu9-54', 'starosta4', 0, 0, 'Magazoff');
--INSERT INTO Lab6.STUDENTS VALUES ('daniil', 20, 1, 'Belgorod', 'iu9-52');
--GO
--COMMIT TRANSACTION;
--GO

--POSSIBLE

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--GO
--BEGIN TRANSACTION;
--INSERT INTO Lab6.GROUPS VALUES ('iu9-54', 'starosta4', 0, 0, 'Magazoff');
--INSERT INTO Lab6.STUDENTS VALUES ('daniil', 20, 1, 'Belgorod', 'iu9-52');
--GO
--COMMIT TRANSACTION;
--GO

--NOT POSSIBLE
--CHANGES WITHIN TRANSACTION

--SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
--GO
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;
--BEGIN TRANSACTION;
--INSERT INTO Lab6.GROUPS VALUES ('iu9-54', 'starosta4', 0, 0, 'Magazoff');
--INSERT INTO Lab6.STUDENTS VALUES ('daniil', 20, 1, 'Belgorod', 'iu9-52');
--GO
--COMMIT TRANSACTION;
--GO
--SELECT * FROM Lab6.GROUPS;
--SELECT * FROM Lab6.STUDENTS;


--NOT POSSIBLE
--WAITS UNTIL FIRST TRANSACTION

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
GO
BEGIN TRANSACTION;
INSERT INTO Lab6.GROUPS VALUES ('iu9-54', 'starosta4', 0, 0, 'Magazoff');
INSERT INTO Lab6.STUDENTS VALUES ('daniil', 20, 1, 'Belgorod', 'iu9-52');
GO
COMMIT TRANSACTION;
GO